baseURL = 'https://ryangoodwin.cv/'
languageCode = 'en-us'
title = "Ryan Goodwin"
theme = 'PaperMod'

[params]
  description = "PhD applicant, theoretical CS / algorithms"
  defaultTheme = "dark"

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/#projects"
  weight = 10
[[menu.main]]
  identifier = "writing"
  name = "Writing"
  url = "/#writing"
  weight = 20
[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/cv.pdf"
  weight = 30

[params.homeInfoParams]
  Content = """
I'm a mathematics and computer science student at Mississippi State University and am interested in pursuing a PhD in <span class="hl-gold">theoretical computer science</span>. 

I write here about math, algorithms, data structures, the books I'm reading, and whatever else has my attention. 

Currently reading *The Count of Monte Cristo*.
"""

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/RDG0818"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ryan-goodwin818/"

[[params.socialIcons]]
  name = "email"
  url = "mailto:ryangoodwin0818@gmail.com"

[markup.goldmark.renderer]
  unsafe = true
